# yaml configuration file for running SPORES
SPORES:
  config_name: "min_molecules(greengas_and_hydrogen)"
  objective_sense: min
  spores_slack: 0.05
  num_spores: 10
  weighting_method: "evolving_average"
  spores_mode: "intensify and diversify"  # Should be either "diversify" or "intensify and diversify"
  diversification_coefficient: 1e8  # Must be a positive number.
  intensification_coefficient: 1e10  # Can be any number with positive for minimization and negative for maximization.
  spore_technologies: # Target technologies when running SPORES.
    - Generator:
        attribute: p_nom
        index:
          - crplein_geothermal_well
          - denhaag_geothermal_well_1
          - denhaag_geothermal_well_2
          - denhaag_geothermal_well_3
          - denhaag_geothermal_well_4
          - tuinders_geothermal_well
          - rotterdam1_geothermal_well_1
          - rotterdam1_geothermal_well_2
          - roca_geothermal_well
          - tuinders_solarthermal
          - indus_waste_heat_point_v
          - indus_waste_heat_rotterdam1

    - Store:
        attribute: e_nom
        index:
          - denhaag_ht_ates_store_1
          - denhaag_ht_ates_store_2
          - denhaag_ht_ates_store_3
          - denhaag_ht_ates_store_4
          - tuinders_ht_ates_store
          - rotterdam1_ht_ates_store

    - StorageUnit:
        attribute: p_nom
        index:
          - cr_plein_storage
          - denhaag_storage
          - tuinders_storage
          - b_triangle_storage
          - rotterdam1_storage
          - roca_storage

    - Link:
        attribute: p_nom
        index:
          - pipe_1
          - pipe_2
          - pipe_3
          - pipe_4
          - pipe_5
          - pipe_6
          - pipe_7
          - pipe_8
          - pipe_9
          - pipe_10
          - pipe_11
          - pipe_12
          - pipe_13
          - pipe_14
          - pipe_15
          - crplein_greengas_boiler
          - crplein_h2_boiler
          - crplein_e_boiler
          - crplein_air_heatpump
          - crplein_chp_greengas_1
          - crplein_chp_greengas_2
          - crplein_chp_hydrogen_1
          - crplein_chp_hydrogen_2
          - crplein_geothermal
          - crplein_geothermal_booster
          - denhaag_greengas_boiler
          - denhaag_h2_boiler
          - denhaag_geothermal_1
          - denhaag_geothermal_1_booster
          - denhaag_e_boiler_1
          - denhaag_air_heatpump_1
          - denhaag_geothermal_2
          - denhaag_geothermal_2_booster
          - denhaag_e_boiler_2
          - denhaag_air_heatpump_2
          - denhaag_geothermal_3
          - denhaag_geothermal_3_booster
          - denhaag_e_boiler_3
          - denhaag_air_heatpump_3
          - denhaag_geothermal_4
          - denhaag_geothermal_4_booster
          - denhaag_e_boiler_4
          - denhaag_air_heatpump_4
          - tuin_tran_greengas_boiler
          - tuin_tran_h2_boiler
          - tuinders_geothermal
          - tuinders_geothermal_booster
          - tuinders_e_boiler
          - tuinders_air_heatpump
          - tuinders_greengas_boiler
          - tuinders_h2_boiler
          - link_indus_waste_heat_to_bus_rotterdam1
          - rotterdam1_greengas_boiler
          - rotterdam1_h2_boiler
          - rotterdam1_geothermal_1
          - rotterdam1_geothermal_1_booster
          - rotterdam1_e_boiler_1
          - rotterdam1_air_heatpump_1
          - rotterdam1_geothermal_2
          - rotterdam1_geothermal_2_booster
          - rotterdam1_e_boiler_2
          - rotterdam1_air_heatpump_2
          - roca_geothermal
          - roca_geothermal_booster
          - roca_e_boiler
          - roca_air_heatpump
          - roca_chp_greengas_1
          - roca_chp_greengas_2
          - roca_chp_greengas_3
          - roca_chp_hydrogen_1
          - roca_chp_hydrogen_2
          - roca_chp_hydrogen_3
          - roca_greengas_boiler
          - roca_h2_boiler
          - waste_incinerator
          - waste_incineration_to_denhaag
          - waste_incineration_to_rotterdam1
          - denhaag_ht_ates_charger_1
          - denhaag_ht_ates_discharger_low_heat_1
          - denhaag_ht_ates_discharger_1
          - denhaag_ht_ates_booster_1
          - denhaag_ht_ates_charger_2
          - denhaag_ht_ates_discharger_low_heat_2
          - denhaag_ht_ates_discharger_2
          - denhaag_ht_ates_booster_2
          - denhaag_ht_ates_charger_3
          - denhaag_ht_ates_discharger_low_heat_3
          - denhaag_ht_ates_discharger_3
          - denhaag_ht_ates_booster_3
          - denhaag_ht_ates_charger_4
          - denhaag_ht_ates_discharger_low_heat_4
          - denhaag_ht_ates_discharger_4
          - denhaag_ht_ates_booster_4
          - tuinders_ht_ates_charger
          - tuinders_ht_ates_discharger_low_heat
          - tuinders_ht_ates_discharger
          - tuinders_ht_ates_booster
          - rotterdam1_ht_ates_charger
          - rotterdam1_ht_ates_discharger_low_heat
          - rotterdam1_ht_ates_discharger
          - rotterdam1_ht_ates_booster

  intensifiable_technologies:  # Subset of spore_technologies to intensify (push to max or min deployment within slack).
    - crplein_greengas_boiler
    - denhaag_greengas_boiler
    - tuin_tran_greengas_boiler
    - tuinders_greengas_boiler
    - rotterdam1_greengas_boiler
    - roca_greengas_boiler
    - crplein_h2_boiler
    - denhaag_h2_boiler
    - tuin_tran_h2_boiler
    - tuinders_h2_boiler
    - rotterdam1_h2_boiler
    - roca_h2_boiler
    - crplein_chp_greengas_1
    - crplein_chp_greengas_2
    - roca_chp_greengas_1
    - roca_chp_greengas_2
    - roca_chp_greengas_3
    - crplein_chp_hydrogen_1
    - crplein_chp_hydrogen_2
    - roca_chp_hydrogen_1
    - roca_chp_hydrogen_2
    - roca_chp_hydrogen_3
